name: stremio-docker
services:
    stremio:
        cpu_shares: 90
        command: []
        container_name: stremio
        deploy:
            resources:
                limits:
                    memory: "7655653376"
        environment:
            AUTO_SERVER_URL: "1"
            NO_CORS: "1"
        hostname: stremio
        image: tsaridas/stremio-docker:latest
        networks:
            default: null
        ports:
            - mode: ingress
              target: 8080
              published: "8080"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /srv/stremio
              target: /root/.stremio-server
              bind:
                create_host_path: true
networks:
    default:
        name: stremio-docker_default
x-casaos:
    author: self
    category: self
    hostname: 192.168.1.32
    icon: ""
    index: /
    is_uncontrolled: false
    port_map: "8080"
    scheme: http
    title:
        custom: Stremio
